// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 25.2
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `persistent/journal.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:coerce.persistent.journal.JournalEntry)
pub struct JournalEntry {
    // message fields
    // @@protoc_insertion_point(field:coerce.persistent.journal.JournalEntry.sequence)
    pub sequence: i64,
    // @@protoc_insertion_point(field:coerce.persistent.journal.JournalEntry.payload_type)
    pub payload_type: ::std::string::String,
    // @@protoc_insertion_point(field:coerce.persistent.journal.JournalEntry.bytes)
    pub bytes: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:coerce.persistent.journal.JournalEntry.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a JournalEntry {
    fn default() -> &'a JournalEntry {
        <JournalEntry as ::protobuf::Message>::default_instance()
    }
}

impl JournalEntry {
    pub fn new() -> JournalEntry {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sequence",
            |m: &JournalEntry| { &m.sequence },
            |m: &mut JournalEntry| { &mut m.sequence },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "payload_type",
            |m: &JournalEntry| { &m.payload_type },
            |m: &mut JournalEntry| { &mut m.payload_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "bytes",
            |m: &JournalEntry| { &m.bytes },
            |m: &mut JournalEntry| { &mut m.bytes },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<JournalEntry>(
            "JournalEntry",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for JournalEntry {
    const NAME: &'static str = "JournalEntry";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.sequence = is.read_int64()?;
                },
                18 => {
                    self.payload_type = is.read_string()?;
                },
                26 => {
                    self.bytes = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.sequence != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.sequence);
        }
        if !self.payload_type.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.payload_type);
        }
        if !self.bytes.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.bytes);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.sequence != 0 {
            os.write_int64(1, self.sequence)?;
        }
        if !self.payload_type.is_empty() {
            os.write_string(2, &self.payload_type)?;
        }
        if !self.bytes.is_empty() {
            os.write_bytes(3, &self.bytes)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> JournalEntry {
        JournalEntry::new()
    }

    fn clear(&mut self) {
        self.sequence = 0;
        self.payload_type.clear();
        self.bytes.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static JournalEntry {
        static instance: JournalEntry = JournalEntry {
            sequence: 0,
            payload_type: ::std::string::String::new(),
            bytes: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for JournalEntry {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("JournalEntry").unwrap()).clone()
    }
}

impl ::std::fmt::Display for JournalEntry {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for JournalEntry {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18persistent/journal.proto\x12\x19coerce.persistent.journal\"c\n\x0c\
    JournalEntry\x12\x1a\n\x08sequence\x18\x01\x20\x01(\x03R\x08sequence\x12\
    !\n\x0cpayload_type\x18\x02\x20\x01(\tR\x0bpayloadType\x12\x14\n\x05byte\
    s\x18\x03\x20\x01(\x0cR\x05bytesb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(JournalEntry::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
