####################################################################################################
## Builder
####################################################################################################
FROM rust:1.60.0 AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates
RUN rustup update

# Create appuser
ENV USER=coerce
ENV UID=10001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"


WORKDIR /sharded-chat-server

COPY . .

RUN cargo build --target x86_64-unknown-linux-musl --release --bin sharded-chat-server

####################################################################################################
## Final image
####################################################################################################
FROM scratch

# Import from builder.
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

WORKDIR /sharded-chat-server

# Copy our build
COPY --from=builder /sharded-chat-server/target/x86_64-unknown-linux-musl/release/sharded-chat-server ./

# Use an unprivileged user.
USER coerce:coerce

CMD ["/sharded-chat-server/sharded-chat-server", ""]