on:
  push:
    branches:
      - master
      - feature/**
      - dev
  pull_request:
    branches:
      - master
  workflow_dispatch:
  
name: coerce-rs tests

jobs:
  build_and_test:
    name: Coerce Runtime Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install redis cluster service
        uses: pfapi/redis-cluster-service@v1
      - name: start redis cluster
        run: sudo systemctl start redis-cluster1
      - name: start redis server
        run: sudo systemctl start redis-server
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features